material:
  conductivity: 16.2  # W/m-K (e.g., for steel)
  density: 7800.0      # kg/m³  
  specific_heat: 500.0 # J/kg-K
  melting_temperature: 1400 # K (e.g., steel melting point)

laser:
  power: 250         # Watts
  spot_size: 1.0e-4    # meters (100 μm, explicitly as float)
  position: [0.25e-3, 0.25e-3]  # Center of top surface
  reflectivity: 0.8    # % reflection (1- absorption)

double_ellipsoid:
  enabled: true      # Toggle between heat source models
  Q: 250              # total power (W)
  a_f: 0.4e-4         # front radius (m)
  a_r: 1.2e-4         # rear radius (m)
  b: 1.0e-4           # y-axis radius (m)
  c: 1.0e-4           # z-axis radius (m)
  f_f: 0.7            # Front fraction of power
  f_r: 1.3            # Rear fraction of power (must satisfy f_f + f_r = 2)
  position: [0.5e-3, 0.5e-3]  # Center position

top_surface:
  convective_cooling: true
  h: 10.0             #  heat transfer coefficient (W/m²K)
  T_inf: 300.0         # K

boundaries:
  front:
    type: adiabatic
  back:
    type: adiabatic  
  left:
    type: adiabatic
  right:
    type: adiabatic
  bottom:
    # type: convective
    # h: 5000.0  # W/m²K (high value for heat sink)
    # T_inf: 300.0  # K
    type: fixed
    fixed_temp : 300.0 # K

simulation:
  duration: 0.05        # seconds
  output_interval: 0.005 # seconds
  max_dt: 1.0e-4       # seconds
  solver_type: "cuda"  # Options: "auto", "cpu", "cuda"

domain:
  size: 1.0e-3         # meters (1mm)
  points_per_dimension: 50  # Grid resolution
